export const site = {
  name: "PotolokX",
  brand: "PotolokX",
  legalName: "PotolokX — Natijnoy potolok Qashqadaryo",
  url: "https://vashpotolok.uz",
  region: "Qashqadaryo viloyati",
  baseCity: "Qarshi",
  phone: "+998908866666",
  phoneDisplay: "+998 90 886 66 66",
  telegram: "vashpotolokbot",
  telegramUrl: "https://t.me/vashpotolokbot",
  instagram: "#",
  email: "info@vashpotolok.uz",
  workingHours: "Har kuni 09:00 — 21:00",
  description:
    "PotolokX — Qarshi va Qashqadaryo bo'ylab natijnoy potolok o'rnatish xizmati. Sifatli material, toza montaj, kafolat va Telegram bot orqali tez narx hisoblash.",
  keywords: [
    "natijnoy patalok qashqadaryo",
    "natijnoy potolok qarshi",
    "natijnoy patalok shahrisabz",
    "potolok ustasi qarshi",
    "natyajnoy potolok",
    "natijniy patalok",
    "natijniy potolok",
    "natyajnoy patalok",
    "натяжной потолок карши",
    "натяжной потолок кашкадарья",
    "натяжные потолки",
    "натяжной потолок нархи",
    "PotolokX",
    "Vashpotolok",
    "natijnoy potolok narxi",
    "natijnoy patalok narxi",
    "potolok montaj qashqadaryo",
    "led potolok qarshi",
    "patalok ustasi",
  ],
};

export type Site = typeof site;
