export const site = {
  name: "Natijnoy Patalok",
  brand: "Natijnoy Patalok",
  legalName: "Natijnoy Patalok Qashqadaryo",
  url: "https://natijnoypatalok.uz",
  partnerName: "Vashpotolok",
  partnerUrl: "https://vashpotolok.uz",
  region: "Qashqadaryo viloyati",
  baseCity: "Qarshi",
  phone: "+998908866666",
  phoneDisplay: "+998 90 886 66 66",
  telegram: "vashpotolokbot",
  telegramUrl: "https://t.me/vashpotolokbot",
  telegramChannelUrl: "https://t.me/vashpotolokuz",
  instagram: "#",
  email: "info@natijnoypatalok.uz",
  workingHours: "Har kuni 09:00 — 21:00",
  description:
    "Natijnoy patalok Qashqadaryo bo'ylab o'rnatish xizmati. Qarshi va tumanlarda o'lchovga chiqamiz. Razmer yuboring — narxini Telegramda hisoblaymiz.",
  keywords: [
    "natijnoy patalok qashqadaryo",
    "natijnoy potolok qarshi",
    "natijnoy patalok shahrisabz",
    "potolok ustasi qarshi",
    "natyajnoy potolok",
    "natijniy patalok",
    "natijniy potolok",
    "natyajnoy patalok",
    "натяжной потолок карши",
    "натяжной потолок кашкадарья",
    "натяжные потолки",
    "натяжной потолок нархи",
    "Natijnoy Patalok",
    "Vashpotolok",
    "natijnoy potolok narxi",
    "natijnoy patalok narxi",
    "potolok montaj qashqadaryo",
    "led potolok qarshi",
    "patalok ustasi",
  ],
};

export type Site = typeof site;
